# Generated by Django 5.0.7 on 2024-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=False),
        ),
    ]
