# Generated by Django 5.0.7 on 2024-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_alter_product_discount_alter_product_price_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
