# Generated by Django 5.0.7 on 2024-08-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_rename_phone_number_order_phone_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
